site_name: "ai-recommendation-engine"
site_description: "Recommendation engine for Spotify's music player"

nav:
  - Introduction: index.md
  - System architecture: system-architecture-template.md

plugins:
  - techdocs-core
